### ISSUE TITLE
Nx workspace not detected

### ISSUE THREAD

**Issue by fabruex** [nrwl/nx-console#2406]
## Current Behavior

Nx workspace is not detected on startup. 

I think it might be something related to the VSCode version. It works fine on 1.96.2

### Failure Logs / Images / Videos
```
xls Client - idle
Nxls Client - starting
Telemetry: production
Nxls Client - idle
Nxls Client - idle
Nxls Client - starting
Graph Machine - undefined, {"context":{"state":"init","project":null,"error":null},"event":{"type":"xstate.init"},"self":{"xstate$$type":1,"id":"x:0"},"system":{"_snapshot":{"_scheduledEvents":{}},"scheduler":{},"_clock":{}}}
Graph - init
Nx Console encountered an error when activating
TypeError: wg.lm.registerTool is not a function
    at YIt (c:\Users\xxx\.vscode\extensions\nrwl.angular-console-18.39.0\main.js:1209:5078)
    at W8 (c:\Users\xxx\.vscode\extensions\nrwl.angular-console-18.39.0\main.js:1373:7067)
    at async a1n (c:\Users\xxx\.vscode\extensions\nrwl.angular-console-18.39.0\main.js:1373:5084)
    at async a.n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:6361)
    at async a.m (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:6324)
    at async a.l (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:5781)
Nxls process started with pid: 26592
Nxls Client - running
``` 

### Environment

Windows

- Nx Console version: 18.39.0
- VSCode version: 1.90.2

**Comment by MaxKless** [comment]
Is there anything in particular stopping you from updating the vscode version? This API exists only on newer versions. I'll make sure to update the vscode manifest accordingly.

**Comment by MaxKless** [comment]
This PR will make the dependency explicit: https://github.com/nrwl/nx-console/pull/2409

In the meantime, I would recommend updating your VSCode

**Comment by fabruex** [comment]
In our company only administrator can update VSCode, and this, unfortunately, doesn't happen every month. Many of my colleagues still have older versions. 

But ok, If this can't be solved with a quick fix I will ask for a "global" update, no problem.

**Comment by MaxKless** [comment]
Thank you! For now you can revert the Nx Console version to fix this, I'm using an API that requires newer versions. You shouldn't have gotten the update had I not forgot to update the required vscode version. That's my bad :/
