### ISSUE TITLE
Cannot run NX Console after updating to v18.21.0 in VS Code

### ISSUE THREAD

**Issue by jorgeruvalcaba** [nrwl/nx-console#2122]
## Current Behavior

After updating to v18.21.0, I get this error when I try to run any nx command:

```
Telemetry: production
Graph - init
Error running task: Cannot find module 'c:/Users/jorge/Code/project/node_modules/nx/src/utils/package-manager'
Require stack:
c:\\Users\\jorge\\.vscode\\extensions\\nrwl.angular-console-18.21.1\\main.js
c:\\Users\\jorge\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\vs\\loader.js
c:\\Users\\jorge\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\bootstrap-amd.js
c:\\Users\\jorge\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\bootstrap-fork.js
```

I had to revert to v18.20.0 in order to use the extension properly.

## Expected Behavior

No errors and the commands running smoothly.

## Steps to Reproduce

1. Open NX Console
2. Click on any listed command

### Environment

```
Node : 20.11.0
   OS   : win32 x64
   npm  : 8.9.0

   nx : 13.8.2
   @nrwl/angular : 13.8.2
   @nrwl/cli : 13.8.2
   @nrwl/cypress : 13.8.2
   @nrwl/devkit : 13.8.2
   @nrwl/eslint-plugin-nx : 13.8.2
   @nrwl/jest : 13.8.2
   @nrwl/linter : 13.8.2
   @nrwl/storybook : 13.8.2
   @nrwl/tao : 13.8.2
   @nrwl/workspace : 13.8.2
   typescript : 4.4.4
   rxjs : 7.5.7
   ---------------------------------------
   Community plugins:
         @angular/animations: 13.3.11
         @angular/cdk: 13.2.3
         @angular/common: 13.3.11
         @angular/compiler: 13.3.11
         @angular/core: 13.3.11
         @angular/forms: 13.3.11
         @angular/material: 13.2.3
         @angular/material-moment-adapter: 13.2.3
         @angular/platform-browser: 13.3.11
         @angular/platform-browser-dynamic: 13.3.11
         @angular/platform-server: 13.3.11
         @angular/router: 13.3.11
         @angular-builders/custom-webpack: 13.1.0
         @angular-devkit/build-angular: 13.3.9
         @angular/cli: 13.2.4
         @angular/compiler-cli: 13.3.11
         @angular/language-service: 13.3.11
         @cypress/schematic: 1.7.0
         ngx-build-plus: 13.0.1
         nx-electron: 13.2.1
```

**Comment by MaxKless** [comment]
Hey! It looks like you're on Nx 13. Nx Console only guarantees compatibility for version 15 & up. If you still run into this issue on a newer version of Nx, let me know and I'll reopen it.
You're always welcome to make a PR - I'd be happy to help out.

**Comment by kopach** [comment]
solution in this case - downgrade VSCode NX extension to previous version, e.g. `v17.32.0` - that should solve the issue with `nx@13` compatibility
